spring:
  thymeleaf:
    cache: false
    mode: HTML
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://10.20.3.220:3306/cis_educational?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.format_sql: false
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: 10.20.3.177
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener.simple.concurrency: 10
    listener.simple.max-concurrency: 10
    listener.simple.prefetch: 1
    listener.simple.auto-startup: true
    listener.simple.default-requeue-rejected: true
    template.retry.enabled: true
    template.retry.initial-interval: 1000
    template.retry.max-attempts: 3
    template.retry.max-interval: 10000
    template.retry.multiplier: 1.0

redis:
  host: 192.168.199.131
  port: 6379
  timeout: 10
#  password: yfshen
  poolMaxTotal: 1500
  poolMaxIdle: 500
  poolMaxWait: 500

  data:
    mongodb:
      host: 192.168.199.131
      database: spitdb
      port: 27017

